#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# E-Press — one-time server bootstrap.
#
# Run ONCE per server as root. Sets up paths, system user (we use root since
# that matches the existing project pattern on this box), Postgres DB + user,
# nginx vhost, certbot, pm2 startup, and the initial git clone.
#
# After this finishes, the day-to-day flow is:
#   GitHub push to main  →  Jenkins build  →  deploy/deploy.sh
#
# Usage on the server (paste once, idempotent — safe to re-run):
#   curl -fsSL https://raw.githubusercontent.com/MoctarSidibe/E_press/main/deploy/install.sh | sudo bash
# or
#   bash /var/www/epress/deploy/install.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Configuration ────────────────────────────────────────────────────────────
PROJECT_NAME="epress"
PROJECT_PATH="/var/www/${PROJECT_NAME}"
REPO_URL="https://github.com/MoctarSidibe/E_press.git"
BRANCH="main"

DB_NAME="epress_prod"
DB_USER="epress_user"

BACKEND_PORT="5004"
DOMAIN="epress.ga"

# ── Helpers ──────────────────────────────────────────────────────────────────
log()  { echo -e "\033[36m[install]\033[0m $*"; }
warn() { echo -e "\033[33m[install]\033[0m $*"; }
err()  { echo -e "\033[31m[install]\033[0m $*" >&2; }
need() { command -v "$1" >/dev/null 2>&1 || { err "missing dep: $1"; exit 1; }; }

# ── Pre-flight ───────────────────────────────────────────────────────────────
[[ "$EUID" -eq 0 ]] || { err "must run as root"; exit 1; }
need git
need node
need npm
need pm2
need nginx
need psql

log "Pre-flight OK"

# ── 1. Clone or update repo ──────────────────────────────────────────────────
if [[ -d "${PROJECT_PATH}/.git" ]]; then
    log "Repo exists, pulling latest from origin/${BRANCH}"
    git -C "${PROJECT_PATH}" fetch origin "${BRANCH}"
    git -C "${PROJECT_PATH}" reset --hard "origin/${BRANCH}"
else
    log "Cloning ${REPO_URL} → ${PROJECT_PATH}"
    mkdir -p "$(dirname "${PROJECT_PATH}")"
    git clone --branch "${BRANCH}" --depth 50 "${REPO_URL}" "${PROJECT_PATH}"
fi

# ── 2. Postgres user + database ──────────────────────────────────────────────
log "Provisioning Postgres role/database (idempotent)"

# Generate password if not already set
PASS_FILE="${PROJECT_PATH}/.deploy-db-pass"
if [[ -f "${PASS_FILE}" ]]; then
    DB_PASSWORD="$(cat "${PASS_FILE}")"
    log "Reusing existing DB password from ${PASS_FILE}"
else
    DB_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
    echo "${DB_PASSWORD}" > "${PASS_FILE}"
    chmod 600 "${PASS_FILE}"
    log "Generated new DB password (stored at ${PASS_FILE}, mode 600)"
fi

sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
   IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DB_USER}') THEN
       CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
   ELSE
       ALTER ROLE ${DB_USER} PASSWORD '${DB_PASSWORD}';
   END IF;
END
\$\$;
SQL

# Create DB if missing
if ! sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw "${DB_NAME}"; then
    sudo -u postgres createdb -O "${DB_USER}" "${DB_NAME}"
    log "Created database ${DB_NAME} owned by ${DB_USER}"
else
    sudo -u postgres psql -c "ALTER DATABASE ${DB_NAME} OWNER TO ${DB_USER};" >/dev/null
    log "Database ${DB_NAME} already exists (ownership ensured)"
fi

# uuid-ossp extension (used by schema.sql)
sudo -u postgres psql -d "${DB_NAME}" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' >/dev/null
log "uuid-ossp extension ensured"

# ── 3. Backend .env ──────────────────────────────────────────────────────────
ENV_FILE="${PROJECT_PATH}/backend/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
    JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
    cat > "${ENV_FILE}" <<ENV
# Generated by deploy/install.sh — do NOT commit
NODE_ENV=production
PORT=${BACKEND_PORT}

DB_HOST=localhost
DB_PORT=5432
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}

JWT_SECRET=${JWT_SECRET}

# Public base URL used in URLs the backend hands to clients
PUBLIC_BASE_URL=https://${DOMAIN}
ENV
    chmod 600 "${ENV_FILE}"
    log "Wrote backend .env (mode 600) with fresh JWT_SECRET"
else
    log "Backend .env already exists — leaving it alone"
fi

# Same for admin-panel production env (build-time)
ADMIN_ENV="${PROJECT_PATH}/admin-panel/.env.production"
if [[ ! -f "${ADMIN_ENV}" ]]; then
    cat > "${ADMIN_ENV}" <<ENV
VITE_API_URL=https://${DOMAIN}/api
ENV
    log "Wrote admin-panel/.env.production"
fi

# ── 4. Install + build ───────────────────────────────────────────────────────
log "Installing backend dependencies"
(cd "${PROJECT_PATH}/backend" && npm ci --omit=dev --no-audit --no-fund)

log "Installing admin dependencies + build"
(cd "${PROJECT_PATH}/admin-panel" && npm ci --no-audit --no-fund && npm run build)

# ── 5. Run migrations ────────────────────────────────────────────────────────
log "Applying schema + migrations"
PGPASSWORD="${DB_PASSWORD}" psql -h localhost -U "${DB_USER}" -d "${DB_NAME}" \
    -v ON_ERROR_STOP=0 \
    -f "${PROJECT_PATH}/backend/database/schema.sql" \
    >/dev/null 2>&1 || warn "schema.sql had errors (might already exist — that's fine)"

for migration in "${PROJECT_PATH}"/backend/database/migrations/*.sql; do
    log "  applying $(basename "${migration}")"
    PGPASSWORD="${DB_PASSWORD}" psql -h localhost -U "${DB_USER}" -d "${DB_NAME}" \
        -v ON_ERROR_STOP=0 -q -f "${migration}" >/dev/null 2>&1 || warn "    (some statements skipped — usually IF NOT EXISTS noise)"
done

# Optional: seed an admin if none exists. We do NOT auto-seed test workers in prod.
if ! PGPASSWORD="${DB_PASSWORD}" psql -h localhost -U "${DB_USER}" -d "${DB_NAME}" -tAc \
    "SELECT 1 FROM users WHERE role = 'admin' LIMIT 1" | grep -q 1; then
    log "No admin user found — running create_admin.js"
    (cd "${PROJECT_PATH}/backend" && node scripts/create_admin.js) || warn "admin seed had issues"
fi

# ── 6. PM2 ───────────────────────────────────────────────────────────────────
log "Starting / reloading backend under pm2"
(cd "${PROJECT_PATH}" && pm2 startOrReload deploy/ecosystem.config.js --env production)
pm2 save --force >/dev/null

# Ensure pm2 starts on boot (idempotent — re-running is a no-op)
pm2 startup systemd -u root --hp /root | tail -1 | sh >/dev/null 2>&1 || true

# ── 7. nginx vhost ───────────────────────────────────────────────────────────
NGINX_SITE="/etc/nginx/sites-available/${PROJECT_NAME}"
if [[ ! -f "${NGINX_SITE}" ]]; then
    cp "${PROJECT_PATH}/deploy/nginx/epress.conf" "${NGINX_SITE}"
    ln -sf "${NGINX_SITE}" "/etc/nginx/sites-enabled/${PROJECT_NAME}"
    log "Installed nginx site ${NGINX_SITE} and enabled it"
else
    log "nginx site ${NGINX_SITE} exists — leaving it alone (edit manually if needed)"
fi

nginx -t && systemctl reload nginx
log "nginx reloaded"

# ── 8. Done ──────────────────────────────────────────────────────────────────
log ""
log "═══════════════════════════════════════════════════════════════════════"
log "Bootstrap complete."
log ""
log "Next steps:"
log "  1. Point DNS A record  ${DOMAIN}  →  $(curl -s ifconfig.me 2>/dev/null || echo '<this server IP>')"
log "  2. Wait for DNS to propagate (a few minutes)"
log "  3. Run SSL:   certbot --nginx -d ${DOMAIN} -d www.${DOMAIN} --redirect --agree-tos -m admin@${DOMAIN} --non-interactive"
log "  4. Backend is on port ${BACKEND_PORT} (pm2 process: ${PROJECT_NAME}-backend)"
log "  5. Quick check:  pm2 logs ${PROJECT_NAME}-backend --lines 30"
log "  6. Smoke test:  cd ${PROJECT_PATH}/backend && node scripts/smoke_test.js https://${DOMAIN}"
log "═══════════════════════════════════════════════════════════════════════"
